/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedChatsRouteImport } from './routes/_authenticated/chats'
import { Route as ApiBotSendMessageRouteImport } from './routes/api/bot/sendMessage'
import { Route as ApiBotMediaRouteImport } from './routes/api/bot/_media'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedChatsRoute = AuthenticatedChatsRouteImport.update({
  id: '/chats',
  path: '/chats',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiBotSendMessageRoute = ApiBotSendMessageRouteImport.update({
  id: '/api/bot/sendMessage',
  path: '/api/bot/sendMessage',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBotMediaRoute = ApiBotMediaRouteImport.update({
  id: '/api/bot/_media',
  path: '/api/bot',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/chats': typeof AuthenticatedChatsRoute
  '/api/bot': typeof ApiBotMediaRoute
  '/api/bot/sendMessage': typeof ApiBotSendMessageRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/chats': typeof AuthenticatedChatsRoute
  '/api/bot': typeof ApiBotMediaRoute
  '/api/bot/sendMessage': typeof ApiBotSendMessageRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/chats': typeof AuthenticatedChatsRoute
  '/api/bot/_media': typeof ApiBotMediaRoute
  '/api/bot/sendMessage': typeof ApiBotSendMessageRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/auth' | '/chats' | '/api/bot' | '/api/bot/sendMessage'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/auth' | '/chats' | '/api/bot' | '/api/bot/sendMessage'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/chats'
    | '/api/bot/_media'
    | '/api/bot/sendMessage'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiBotMediaRoute: typeof ApiBotMediaRoute
  ApiBotSendMessageRoute: typeof ApiBotSendMessageRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/chats': {
      id: '/_authenticated/chats'
      path: '/chats'
      fullPath: '/chats'
      preLoaderRoute: typeof AuthenticatedChatsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/bot/sendMessage': {
      id: '/api/bot/sendMessage'
      path: '/api/bot/sendMessage'
      fullPath: '/api/bot/sendMessage'
      preLoaderRoute: typeof ApiBotSendMessageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/bot/_media': {
      id: '/api/bot/_media'
      path: '/api/bot'
      fullPath: '/api/bot'
      preLoaderRoute: typeof ApiBotMediaRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedChatsRoute: typeof AuthenticatedChatsRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedChatsRoute: AuthenticatedChatsRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiBotMediaRoute: ApiBotMediaRoute,
  ApiBotSendMessageRoute: ApiBotSendMessageRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
